---
- name: Create multi-container architecture
  hosts: all
  become: yes
  tasks:
    - name: Create mysql container
      docker_container:
        name: mydb
        image: mysql:5
        env:
          MYSQL_ROOT_PASSWORD: xyz
    - name: Create a wordpress container linked with msql
      docker_container:
        name: mywordpress
        image: wordpress
        ports:
          - 9999:80
        links:
          - mydb:mysql
...
