---
- name: Implementing tags
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Install tree
      apt:
        name: tree
        state: present
        update_cache: yes
      tags: tree_installation

    - name: Create user
      user:
        name: Anu
        password: abc
      tags: user_creation

    - name: copy the passwd file
      copy:
        src: /etc/passwd
        dest: /tmp
...
