---
- name: install docker and req. s/s's
  hosts: all
  tasks:
    - name: install python3-pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    - name: download, execute and install docker and docker-py
      shell: "{{item}}"
      with_items:
        - curl -fsSL https://get.docker.com -o get-docker.sh
        - sh get-docker.sh
        - pip3 install docker-py
...
