---
- name: Complete setup of Tomcat9
  hosts: all
  tasks:
    - name: Install tomcat9
      apt:
        name: tomcat9
        state: present
        update_cache: yes
    - name: Install tomcat9-admin
      apt:
        name: tomcat9-admin
        state: present
    - name: Change port from 8080 to 9090
      replace:
        regexp: 9090
        replace: 8080
        path: /etc/tomcat9/server.xml
    - name: Copy tomcat-user.xml file
      copy:
        src: /home/ubuntu/tomcat-users.xml
        dest: /etc/tomcat9/
    - name: Restart tomcat9 service
      service:
        name: tomcat9
        state: restarted
    - name: Pause playbook execution for 1 minute
      pause:
        minutes: 1
    - name: Check tomcat url response of server1
      uri:
        url: http://54.160.99.176:8080
        status_code: 200
    - name: Check tomcat url respone of server2
      uri:
        url: http://54.157.189.130:8080
        status_code: 200
...
