---
- name: if file is executable, delete it
  hosts: all
  tasks:
    - name: check file1
      stat:
        path: file1
      register: a
    - name: display output of file1
      debug:
        var: a
    - name: delete file if it is executable
      file:
        name: file1
        state: absent
      when: a.stat.executable == true

...
