---
- name: installing s/s using loop
  hosts: all
  tasks:
    - name: install s/w
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - tree
        - git
        - maven
...

