---
- name: Create user and file in it
  hosts: all
  tasks:
    - name: create user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: create file in respected user
      file:
        name: "{{d}}"
        state: "{{e}}"
...
