---
- name: create user using host scope variable
  hosts: 172.31.48.153
  tasks:
    - name: create user
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        comment: "{{d}}"
        home: "{{e}}"
        shell: "{{f}}"
...
